api_platform_pdg:
  autoload: 'vendor/autoload.php'
  database_dir: './var/databases'
  reference:
    src: '/home/hugo/Documents/Tilleuls/Forks/core/src'
    namespace: 'ApiPlatform'
    patterns:
      directories: ['Metadata', 'OpenApi/Model']
      names: ["*Interface.php", "*Trait.php", "Configuration.php"]]
      exclude: ['*Factory.php']
      class_tags_to_ignore: ['@experimental', '@internal']
  target:
    directories:
      guide_path: 'pages/guide'
      reference_path: 'pages/reference'

    base_path: 'pages'
