name: Build

on:
  pull_request: ~
#  push:
#    tags:
#      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Update project dependencies
        run: composer update --no-progress --ansi --prefer-stable --no-dev --optimize-autoloader
      - name: Install Box Project
        run: composer global require humbug/box
      - name: Run Box Project
        run: box compile
      - name: Upload phar artifact
        uses: actions/upload-artifact@v3
        with:
          name: pdg.phar
          path: bin/pdg.phar
#      - name: Create release
#        if: false
#        run: |
#          gh api -X POST \n
#            -H "Accept: application/vnd.github+json" \n
#            /repos/${{ github.repository }}/releases \n
#            -f target_commitish='main' \n
#            -f tag_name='v0.0.1' \n
#            -f name='v0.0.1' \n
#            -F draft=false \n
#            -F prelease=false \n
#            -F generate_release_notes=true \n
#            -F make_latest=true
#      - name: Upload phar to release
#        run: |
#          gh api \
#            --method POST \
#            -H "Accept: application/vnd.github+json" \
#            /repos/${{ github.repository }}/releases/91232019/assets?name=pdg.phar \
#            -f '@bin/pdg.phar'
      - name: Create release if necessary, and upload phar to it
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_SECRET }}
          file: bin/pdg.phar
          asset_name: pdg.phar
          tag: v0.0.1
          release_name: v0.0.1
#          tag: ${{ github.ref_name }}
#          release_name: ${{ github.ref_name }}
          overwrite: false
