name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request: ~
  schedule:
    # Every Sunday at 02:00
    - cron: 0 2 * * 0

jobs:
  tests:
    name: Tests PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2']
      fail-fast: false
    env:
      # PHP CS Fixer does not support PHP 8.2 yet
      PHP_CS_FIXER_IGNORE_ENV: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
      - name: Conventional commit check
        uses: cocogitto/cocogitto-action@v3
        with:
          git-user: 'github-actions'
          git-user-email: 'github-actions@github.com'
          check-latest-tag-only: true
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, php-cs-fixer, phpstan, phpdoc
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Update project dependencies
        run: composer update --no-progress --ansi --prefer-stable
      - name: Install PHPUnit
        run: vendor/bin/simple-phpunit --version
      - name: Run php-cs-fixer tests
        run: php-cs-fixer fix --diff --dry-run --ansi --verbose
      - name: Cache PHPStan
        uses: actions/cache@v3
        with:
          path: .phpstan/
          key: phpstan-${{ github.sha }}
          restore-keys: phpstan-
      - name: Run PHPStan tests
        run: phpstan analyze src tests
      - name: Run PHPUnit tests
        run: vendor/bin/simple-phpunit --coverage-clover build/logs/phpunit/clover.xml
      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-php${{ matrix.php }}
          path: build

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Update project dependencies
        run: composer update --no-progress --ansi --prefer-stable --no-dev --optimize-autoloader
      - name: Install Box Project
        run: composer global require humbug/box
      - name: Run Box Project
        run: box compile
