on:
  workflow_dispatch:
    branches: main

jobs:
  release:
    name: Perform release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
      - name: Cocogitto release
        id: release
        uses: oknozor/cocogitto-action@v3.4
        with:
          release: true
          git-user: 'github-actions'
          git-user-email: 'github-actions@github.com'
      - name: Generate Changelog
        run: cog changelog --at ${{ steps.release.outputs.version }} -t full_hash > GITHUB_CHANGELOG.md
      - name: Upload github release
        uses: softprops/action-gh-release@v1
        with:
          body_path: GITHUB_CHANGELOG.md
          tag_name: ${{ steps.release.outputs.version }}
          
  build:
  name: Build
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        tools: composer:v2
    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-
    - name: Update project dependencies
      run: composer update --no-progress --ansi --prefer-stable --no-dev --optimize-autoloader
    - name: Install Box Project
      run: composer global require humbug/box
    - name: Run Box Project
      run: box compile
    - name: Upload phar artifact
      uses: actions/upload-artifact@v3
      with:
        name: pdg.phar
        path: bin/pdg.phar
